services:
  db:
    image: postgres:16.9-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - surveys-net

  api:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${API_PORT}:3001
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - surveys-net

networks:
  surveys-net:
    driver: bridge

volumes:
  db_data:
