services:
  api:
    build: .
    container_name: api
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:16.9-alpine3.22
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
